export enum WeatherActionTypes {
    FETCH_WEATHER_START = 'FETCH_WEATHER_START',
    FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS',
     FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR',
    SELECT_CITY="SELECT_CITY"
  }
  export enum AppActionTypes {
    TOGGLE_DARK_MODE ='TOGGLE_DARK_MODE',
    TOGGLE_HOURLY_WEEKLY='TOGGLE_HOURLY_WEEKLY'
  }